on: [push]

jobs:
  rust:
    name: Rust projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: rust-lang/rust
          fetch-depth: 1
      - name: collect CPU statistics
        run: src/ci/scripts/collect-cpu-stats.sh

      - name: sleep
        run: sleep 10

      - uses: meysam81/simpleinfra/github-actions/upload-metrics-artifact@meysam/feat/upload-metrics-artifact-action
